[project]
name = "zombie"
version = "0.0.3"
authors = ["Simon Wollwage"]
license = "BSD-3-Clause"
description = "A safe way to remove any zombie child processes (unix/linux only)"

[dependencies]
libc = "0.2.1"

[lib]
name = "zombie"
path = "src/lib.rs"
crate-type = ["rlib"]
